"""
PDF report generator for AMR resistance profiles.

Given a list of prediction results, generates a clean clinical-style
one-page PDF report with:
  - Header (genome ID / source, date, organism)
  - Resistance profile table (antibiotic, verdict, probability bar)
  - MDR summary
  - Disclaimer footer

Returns bytes that Streamlit can pass to st.download_button().
"""

import io
from datetime import datetime
from fpdf import FPDF, XPos, YPos


# Colour palette (RGB)
C_BG      = (30,  30,  46)   # #1e1e2e — dark background
C_PANEL   = (24,  24,  37)   # #181825 — card background
C_RED     = (233, 69,  96)   # #e94560 — resistant
C_GREEN   = (80,  250, 123)  # #50fa7b — susceptible
C_ORANGE  = (255, 184, 108)  # #ffb86c — uncertain
C_TEXT    = (205, 214, 244)  # #cdd6f4 — main text
C_MUTED   = (98,  114, 164)  # #6272a4 — muted text
C_WHITE   = (255, 255, 255)
C_DARK    = (20,  20,  30)


def _bar_color(verdict: str) -> tuple:
    return C_RED if verdict == "Resistant" else C_GREEN if verdict == "Susceptible" else C_ORANGE


def _s(text: str) -> str:
    """Sanitise text to latin-1 safe characters for Helvetica PDF font."""
    return (text
            .replace("–", "-").replace("—", "-")   # en/em dash
            .replace("’", "'").replace("‘", "'")   # curly quotes
            .replace("“", '"').replace("”", '"')   # curly double quotes
            .replace("·", ".")                           # middle dot
            .encode("latin-1", errors="replace").decode("latin-1"))


class AMRReport(FPDF):
    def __init__(self, genome_id: str, source: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.genome_id  = genome_id
        self.source     = source
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Dark header bar
        self.set_fill_color(*C_BG)
        self.rect(0, 0, 210, 28, style="F")

        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*C_RED)
        self.set_xy(15, 6)
        self.cell(80, 8, "AMR Predictor", new_x=XPos.RIGHT, new_y=YPos.TOP)  # noqa

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*C_MUTED)
        self.set_xy(15, 15)
        self.cell(0, 5, "K. pneumoniae Antibiotic Resistance Report")

        # Date top-right
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*C_MUTED)
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.set_xy(150, 10)
        self.cell(45, 5, date_str, align="R")

        self.ln(18)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*C_MUTED)
        self.cell(0, 4,
            "! For research purposes only. Not for clinical use without laboratory confirmation.",
            align="C")
        self.ln(4)
        self.cell(0, 4,
            f"Generated by AMR Predictor | github.com/skazgan/amr-predictor | Page {self.page_no()}",
            align="C")


def generate_pdf(
    predictions: list[dict],
    genome_id:   str = "Unknown",
    source:      str = "BV-BRC",
    extra_info:  dict | None = None,
) -> bytes:
    """
    Generate a PDF report.

    predictions: list of dicts with keys:
        antibiotic, short, drug_class, prob_r, verdict
    extra_info: optional dict of additional fields to show (e.g. country, year)

    Returns: bytes of the PDF.
    """
    pdf = AMRReport(genome_id=genome_id, source=source)
    pdf.add_page()

    # ── Genome info panel ─────────────────────────────────────────────────────
    pdf.set_fill_color(*C_PANEL)
    pdf.set_draw_color(*C_BG)
    pdf.rect(15, pdf.get_y(), 180, 24, style="F")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_TEXT)
    pdf.set_xy(20, pdf.get_y() + 4)
    pdf.cell(40, 5, "Genome / Sample:")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 5, _s(genome_id[:60]))

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_MUTED)
    pdf.set_xy(20, pdf.get_y() + 6)
    pdf.cell(40, 5, "Organism:")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(60, 5, "Klebsiella pneumoniae")

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_MUTED)
    pdf.set_xy(110, pdf.get_y())
    pdf.cell(25, 5, "Source:")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(0, 5, source)

    if extra_info:
        pdf.set_xy(20, pdf.get_y() + 5)
        for k, v in list(extra_info.items())[:4]:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*C_MUTED)
            pdf.cell(35, 4, _s(f"{k}:"))
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*C_TEXT)
            pdf.cell(50, 4, _s(str(v)[:25]))
    else:
        pdf.ln(5)

    pdf.ln(10)

    # ── MDR summary ───────────────────────────────────────────────────────────
    n_r = sum(1 for p in predictions if p["verdict"] == "Resistant")
    n_s = sum(1 for p in predictions if p["verdict"] == "Susceptible")
    n_u = sum(1 for p in predictions if p["verdict"] == "Uncertain")
    is_mdr = n_r >= 3

    # Coloured MDR badge
    badge_color = C_RED if is_mdr else C_GREEN
    pdf.set_fill_color(*badge_color)
    pdf.rect(15, pdf.get_y(), 180, 12, style="F")
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*C_DARK)
    pdf.set_xy(15, pdf.get_y() + 2)
    label = f"[!] MULTI-DRUG RESISTANT (resistant to {n_r} antibiotics)" if is_mdr else "[OK] NOT MDR (resistant to fewer than 3 antibiotics)"
    pdf.cell(0, 7, label, align="C")
    pdf.ln(14)

    # Summary counts row
    for label, count, color in [
        ("Resistant", n_r, C_RED),
        ("Uncertain", n_u, C_ORANGE),
        ("Susceptible", n_s, C_GREEN),
    ]:
        pdf.set_fill_color(*color)
        pdf.rect(pdf.get_x(), pdf.get_y(), 56, 10, style="F")
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*C_DARK)
        pdf.cell(56, 10, f"{label}: {count}", align="C")
        pdf.set_x(pdf.get_x() + 4)
    pdf.ln(14)

    # ── Resistance profile table ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(0, 7, "Resistance Profile", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(1)

    # Table header
    pdf.set_fill_color(*C_BG)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_MUTED)
    col_w = [42, 48, 28, 18, 44]
    headers = ["Antibiotic", "Drug Class", "Verdict", "P(R)", "Confidence"]
    for h, w in zip(headers, col_w):
        pdf.cell(w, 6, h, fill=True)
    pdf.ln(6)

    # Rows
    for i, pred in enumerate(sorted(predictions, key=lambda x: -x["prob_r"])):
        verdict = pred["verdict"]
        prob_r  = pred["prob_r"]
        row_fill = (i % 2 == 0)

        if row_fill:
            pdf.set_fill_color(*C_PANEL)
        else:
            pdf.set_fill_color(*C_BG)

        row_y = pdf.get_y()
        row_x = pdf.get_x()

        # Antibiotic name
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_TEXT)
        pdf.cell(col_w[0], 8, _s(pred["antibiotic"][:24]), fill=row_fill)

        # Drug class
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(col_w[1], 8, _s(pred.get("drug_class", "")[:22]), fill=row_fill)

        # Verdict (coloured)
        vc = _bar_color(verdict)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*vc)
        pdf.cell(col_w[2], 8, _s(verdict), fill=row_fill)

        # Probability
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(*C_TEXT)
        pdf.cell(col_w[3], 8, f"{prob_r:.0%}", fill=row_fill, align="R")

        # Probability bar (drawn manually)
        bar_x = pdf.get_x() + 1
        bar_y = row_y + 2
        bar_total = col_w[4] - 4
        bar_filled = int(prob_r * bar_total)
        # Background
        pdf.set_fill_color(45, 45, 68)
        pdf.rect(bar_x, bar_y, bar_total, 4, style="F")
        # Filled portion
        pdf.set_fill_color(*vc)
        if bar_filled > 0:
            pdf.rect(bar_x, bar_y, bar_filled, 4, style="F")

        pdf.ln(8)

    pdf.ln(6)

    # ── Interpretation notes ──────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_TEXT)
    pdf.cell(0, 6, "Interpretation Notes", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    notes = [
        ("Model", "XGBoost + Random Forest ensemble (60/40 soft-voting), calibrated with isotonic regression"),
        ("Features", "~256 top k-mers (6-mer frequencies) + ~1,600 resistance gene presence/absence flags"),
        ("Training data", "16,902 K. pneumoniae genomes from BV-BRC (2000–2024, 74 countries)"),
        ("Threshold", "Resistant if P(R) ≥ 65%; Susceptible if P(R) ≤ 35%; Uncertain otherwise"),
        ("Accuracy", "AUC range 0.785–0.882 across 10 antibiotics (5-fold cross-validation)"),
    ]

    pdf.set_font("Helvetica", "", 8)
    for label, note in notes:
        pdf.set_text_color(*C_MUTED)
        pdf.cell(38, 5, _s(f"  {label}:"))
        pdf.set_text_color(*C_TEXT)
        pdf.cell(0, 5, _s(note[:90]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
